![imagen](real_state.png)

# Exercise 1

The purpose of this notebook is to demonstrate how to use the features of Python libraries to explore a dataset.

# 1. Import libraries

In [5]:
# System command library
import os 
# Data handling libraries
import pandas as pd 
import numpy as np 
# Machine learning libraries.
# To split the training set into training and test sets.
from sklearn.model_selection import train_test_split
# To build a model using the linear regression algorithm
from sklearn.linear_model import LinearRegression
# To evaluate model performance using MSE, MAE, and R² metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
# To generate a statistical report that can be used to determine the importance of explanatory variables.
import statsmodels.api as sm 

# 2. Load data

In [3]:
data=pd.read_csv('venta_inmuebles_data.csv',sep=',')

In [4]:
data.head()

,numero_cuartos,numero_baños,area_de_ construcción_pie2,area_del lote_pie2,numero_pisos,condición,grado,superficie_sótano_pie2,año_de_construcción,precio
0,3,1,1180,5650,1,3,7,0,1955,221900
1,2,1,770,10000,1,3,6,0,1933,180000
2,4,3,1960,5000,1,5,7,910,1965,604000
3,3,2,1680,8080,1,3,8,0,1987,510000
4,3,1,1780,7470,1,3,7,730,1960,229500


# 3. Data preparation

In [19]:
data_t = data

In [20]:
data_t[data_t.isnull().any(axis=1)]

,numero_cuartos,numero_baños,area_de_ construcción_pie2,area_del lote_pie2,numero_pisos,condición,grado,superficie_sótano_pie2,año_de_construcción,precio


There are no missing values.

In [21]:
data_t[data_t.duplicated()]

,numero_cuartos,numero_baños,area_de_ construcción_pie2,area_del lote_pie2,numero_pisos,condición,grado,superficie_sótano_pie2,año_de_construcción,precio
1193,2,2,1070,649,2,3,9,350,2008,259950


In [22]:
data_t=data_t.drop_duplicates()

In [23]:
data_t[data_t.duplicated()]

,numero_cuartos,numero_baños,area_de_ construcción_pie2,area_del lote_pie2,numero_pisos,condición,grado,superficie_sótano_pie2,año_de_construcción,precio


Remove duplicates

Prior to model construction, a data quality check was performed. No missing values were found in the dataset, and duplicate rows were identified and removed. Additionally, all variables are numeric, which meets the necessary requirements for implementing a linear regression model. Therefore, the data is in optimal condition to proceed with the modeling phase.

# 4. Model Building

In [24]:
# The target variable is selected, in this case "precio".
Y=data_t['precio']
# The “precio” variable is removed from the dataset.
X=data_t.drop(['precio'], axis=1)

In [25]:
X.head()

,numero_cuartos,numero_baños,area_de_ construcción_pie2,area_del lote_pie2,numero_pisos,condición,grado,superficie_sótano_pie2,año_de_construcción
0,3,1,1180,5650,1,3,7,0,1955
1,2,1,770,10000,1,3,6,0,1933
2,4,3,1960,5000,1,5,7,910,1965
3,3,2,1680,8080,1,3,8,0,1987
4,3,1,1780,7470,1,3,7,730,1960


In [26]:
Y.head()

0    221900
1    180000
2    604000
3    510000
4    229500
Name: precio, dtype: int64

Split the data into a training set and a test set. This division allows you to determine the model's generalization performance on new data.

Training data: used to train the model with the learning algorithm.
Test data: used to evaluate the model's fit.

In [27]:
# 20% of the data is set aside for testing.
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.2, random_state=0)

In [28]:
# Create the object to build the model
modelo_regresion = LinearRegression()
modelo_regresion

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [29]:
# Train the model using the training set.
modelo_regresion.fit(X_train,Y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


# 5. Model evaluation

In [38]:
# First, I retrieve the metrics from the training data
y_pred = modelo_regresion.predict(X_train)

print(f"MSE: {mean_squared_error(Y_train, y_pred):.2f}")
print(f"MAE: {mean_absolute_error(Y_train, y_pred):.2f}")
print(f"R²: {r2_score(Y_train, y_pred):.2f}")

MSE: 16003712845.34
MAE: 95901.18
R²: 0.50


In [39]:
y_pred = modelo_regresion.predict(X_test)

print(f"MSE: {mean_squared_error(Y_test, y_pred):.2f}")
print(f"MAE: {mean_absolute_error(Y_test, y_pred):.2f}")
print(f"R²: {r2_score(Y_test, y_pred):.2f}")

MSE: 14565133371.50
MAE: 95100.90
R²: 0.54


In [40]:
modelo_regresion.fit(X,Y)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [41]:
modelo_regresion.coef_

array([-1.70410540e+04,  3.20249718e+04,  7.88881222e+01,  1.09289075e-01,
        4.66920658e+04,  1.09592862e+04,  8.91535637e+04,  1.81523616e+01,
       -2.50647984e+03])

# 6. Models interpretation

In [43]:
model = sm.OLS(Y, X).fit() ## sm.OLS(output, input)
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                 precio   R-squared (uncentered):                   0.900
Model:                            OLS   Adj. R-squared (uncentered):              0.900
Method:                 Least Squares   F-statistic:                              5470.
Date:                Thu, 07 May 2026   Prob (F-statistic):                        0.00
Time:                        17:05:39   Log-Likelihood:                         -72308.
No. Observations:                5465   AIC:                                  1.446e+05
Df Residuals:                    5456   BIC:                                  1.447e+05
Df Model:                           9                                                  
Covariance Type:            nonrobust                                                  
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
numero_cuartos             -1.903e+04   2628.468     -7.239      0.000   -2.42e+04   -1.39e+04
numero_baños               -1530.7478   4190.533     -0.365      0.715   -9745.864    6684.368
area_de_ construcción_pie2    81.6265      5.754     14.185      0.000      70.346      92.908
area_del lote_pie2             0.0791      0.042      1.906      0.057      -0.002       0.161
numero_pisos                4.313e+04   5445.626      7.919      0.000    3.24e+04    5.38e+04
condición                   2.538e+04   2641.505      9.607      0.000    2.02e+04    3.06e+04
grado                       7.581e+04   2916.489     25.995      0.000    7.01e+04    8.15e+04
superficie_sótano_pie2        47.1671      6.752      6.985      0.000      33.930      60.404
año_de_construcción         -179.2292     10.487    -17.090      0.000    -199.789    -158.670
==============================================================================
Omnibus:                      875.262   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2140.377
Skew:                           0.900   Prob(JB):                         0.00
Kurtosis:                       5.481   Cond. No.                     1.48e+05
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.48e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# 7. Conclusions

#### Overall Model Performance
The model explains 90% of the price variability (R-squared = 0.900), indicating excellent predictive power.
The model is statistically significant, with an F-statistic of 5470 and a p-value of 0.00. This confirms that the independent variables collectively have explanatory power over the price.

#### Variable Significance
Most variables are statistically significant, with the following exceptions:

- `numero_baños` (p = 0.715): Not significant. Consider removing this variable.
- `area_del_lote_pie2` (p = 0.057): Very close to the 0.05 threshold. Could be considered marginally significant.

#### Negative Coefficients
Two variables show unexpected negative coefficients:

| Variable | Coefficient | Interpretation |
|----------|-------------|----------------|
| `numero_cuartos` | -19,030 € | Each additional room decreases the price |
| `año_de_construcción` | -179 € | Newer properties decrease in price |

These counterintuitive results are likely explained by multicollinearity (see below).

#### Model Diagnostics

| Test | Value | Interpretation |
|------|-------|----------------|
| **Durbin-Watson** | 1.99 | Close to 2 → No evidence of strong autocorrelation in residuals. Good. |
| **Omnibus (p)** | 0.00 | Residuals do not follow a perfect normal distribution |
| **Jarque-Bera (p)** | 0.00 | Confirms non-normality of residuals |
| **Condition Number** | 148,000 | Very high → Indicates severe multicollinearity |

#### Multicollinearity Issue
The high condition number (148,000) suggests:

- Predictor variables are correlated with each other
- Large scale differences between variables
- Potential numerical instability
- Explains the negative coefficients observed in `numero_cuartos` and `año_de_construcción`

#### Recommendations

1. Check multicollinearity using VIF (Variance Inflation Factor)
2. Consider removing `numero_baños` (not significant)
3. Standardize variables to address scale differences
4. Eliminate redundant variables to reduce multicollinearity
5. Consider transformations (e.g., log of price) to address non-normal residuals